const GET_COUNTRIES_BY_SEARCH_TERM_SAGA = 'app/search/GET_COUNTRIES_BY_SEARCH_TERM_SAGA';
const SET_ALL_COUNTRIES = 'app/search/SET_ALL_COUNTRIES';
const SET_OPTIONS = 'app/search/SET_OPTIONS';
const RESET_OPTIONS = 'app/search/RESET_OPTIONS';
const GET_CURRENT_LOCATION_SAGA = 'app/search/GET_CURRENT_LOCATION';
const SET_CURRENT_LOCATION = 'app/search/SET_CURRENT_LOCATION';

export {
  GET_COUNTRIES_BY_SEARCH_TERM_SAGA,
  SET_ALL_COUNTRIES,
  SET_OPTIONS,
  RESET_OPTIONS,
  GET_CURRENT_LOCATION_SAGA,
  SET_CURRENT_LOCATION,
};
